name: pre-commit

on:
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Run pre-commit
      run: |
        pre-commit run --all-files
